package ca.studymedia.dao.mybatis.example;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CertificationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table certification
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table certification
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table certification
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certification
     *
     * @mbg.generated
     */
    public CertificationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certification
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certification
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certification
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certification
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certification
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certification
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certification
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certification
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certification
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certification
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table certification
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserUseridIsNull() {
            addCriterion("User_UserID is null");
            return (Criteria) this;
        }

        public Criteria andUserUseridIsNotNull() {
            addCriterion("User_UserID is not null");
            return (Criteria) this;
        }

        public Criteria andUserUseridEqualTo(Integer value) {
            addCriterion("User_UserID =", value, "userUserid");
            return (Criteria) this;
        }

        public Criteria andUserUseridNotEqualTo(Integer value) {
            addCriterion("User_UserID <>", value, "userUserid");
            return (Criteria) this;
        }

        public Criteria andUserUseridGreaterThan(Integer value) {
            addCriterion("User_UserID >", value, "userUserid");
            return (Criteria) this;
        }

        public Criteria andUserUseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("User_UserID >=", value, "userUserid");
            return (Criteria) this;
        }

        public Criteria andUserUseridLessThan(Integer value) {
            addCriterion("User_UserID <", value, "userUserid");
            return (Criteria) this;
        }

        public Criteria andUserUseridLessThanOrEqualTo(Integer value) {
            addCriterion("User_UserID <=", value, "userUserid");
            return (Criteria) this;
        }

        public Criteria andUserUseridIn(List<Integer> values) {
            addCriterion("User_UserID in", values, "userUserid");
            return (Criteria) this;
        }

        public Criteria andUserUseridNotIn(List<Integer> values) {
            addCriterion("User_UserID not in", values, "userUserid");
            return (Criteria) this;
        }

        public Criteria andUserUseridBetween(Integer value1, Integer value2) {
            addCriterion("User_UserID between", value1, value2, "userUserid");
            return (Criteria) this;
        }

        public Criteria andUserUseridNotBetween(Integer value1, Integer value2) {
            addCriterion("User_UserID not between", value1, value2, "userUserid");
            return (Criteria) this;
        }

        public Criteria andResourceResourceidIsNull() {
            addCriterion("Resource_ResourceID is null");
            return (Criteria) this;
        }

        public Criteria andResourceResourceidIsNotNull() {
            addCriterion("Resource_ResourceID is not null");
            return (Criteria) this;
        }

        public Criteria andResourceResourceidEqualTo(Integer value) {
            addCriterion("Resource_ResourceID =", value, "resourceResourceid");
            return (Criteria) this;
        }

        public Criteria andResourceResourceidNotEqualTo(Integer value) {
            addCriterion("Resource_ResourceID <>", value, "resourceResourceid");
            return (Criteria) this;
        }

        public Criteria andResourceResourceidGreaterThan(Integer value) {
            addCriterion("Resource_ResourceID >", value, "resourceResourceid");
            return (Criteria) this;
        }

        public Criteria andResourceResourceidGreaterThanOrEqualTo(Integer value) {
            addCriterion("Resource_ResourceID >=", value, "resourceResourceid");
            return (Criteria) this;
        }

        public Criteria andResourceResourceidLessThan(Integer value) {
            addCriterion("Resource_ResourceID <", value, "resourceResourceid");
            return (Criteria) this;
        }

        public Criteria andResourceResourceidLessThanOrEqualTo(Integer value) {
            addCriterion("Resource_ResourceID <=", value, "resourceResourceid");
            return (Criteria) this;
        }

        public Criteria andResourceResourceidIn(List<Integer> values) {
            addCriterion("Resource_ResourceID in", values, "resourceResourceid");
            return (Criteria) this;
        }

        public Criteria andResourceResourceidNotIn(List<Integer> values) {
            addCriterion("Resource_ResourceID not in", values, "resourceResourceid");
            return (Criteria) this;
        }

        public Criteria andResourceResourceidBetween(Integer value1, Integer value2) {
            addCriterion("Resource_ResourceID between", value1, value2, "resourceResourceid");
            return (Criteria) this;
        }

        public Criteria andResourceResourceidNotBetween(Integer value1, Integer value2) {
            addCriterion("Resource_ResourceID not between", value1, value2, "resourceResourceid");
            return (Criteria) this;
        }

        public Criteria andDateIsNull() {
            addCriterion("date is null");
            return (Criteria) this;
        }

        public Criteria andDateIsNotNull() {
            addCriterion("date is not null");
            return (Criteria) this;
        }

        public Criteria andDateEqualTo(Date value) {
            addCriterion("date =", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotEqualTo(Date value) {
            addCriterion("date <>", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateGreaterThan(Date value) {
            addCriterion("date >", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateGreaterThanOrEqualTo(Date value) {
            addCriterion("date >=", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLessThan(Date value) {
            addCriterion("date <", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLessThanOrEqualTo(Date value) {
            addCriterion("date <=", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateIn(List<Date> values) {
            addCriterion("date in", values, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotIn(List<Date> values) {
            addCriterion("date not in", values, "date");
            return (Criteria) this;
        }

        public Criteria andDateBetween(Date value1, Date value2) {
            addCriterion("date between", value1, value2, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotBetween(Date value1, Date value2) {
            addCriterion("date not between", value1, value2, "date");
            return (Criteria) this;
        }

        public Criteria andGradeIsNull() {
            addCriterion("grade is null");
            return (Criteria) this;
        }

        public Criteria andGradeIsNotNull() {
            addCriterion("grade is not null");
            return (Criteria) this;
        }

        public Criteria andGradeEqualTo(Integer value) {
            addCriterion("grade =", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotEqualTo(Integer value) {
            addCriterion("grade <>", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeGreaterThan(Integer value) {
            addCriterion("grade >", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeGreaterThanOrEqualTo(Integer value) {
            addCriterion("grade >=", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeLessThan(Integer value) {
            addCriterion("grade <", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeLessThanOrEqualTo(Integer value) {
            addCriterion("grade <=", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeIn(List<Integer> values) {
            addCriterion("grade in", values, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotIn(List<Integer> values) {
            addCriterion("grade not in", values, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeBetween(Integer value1, Integer value2) {
            addCriterion("grade between", value1, value2, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotBetween(Integer value1, Integer value2) {
            addCriterion("grade not between", value1, value2, "grade");
            return (Criteria) this;
        }

        public Criteria andQualifierIsNull() {
            addCriterion("qualifier is null");
            return (Criteria) this;
        }

        public Criteria andQualifierIsNotNull() {
            addCriterion("qualifier is not null");
            return (Criteria) this;
        }

        public Criteria andQualifierEqualTo(String value) {
            addCriterion("qualifier =", value, "qualifier");
            return (Criteria) this;
        }

        public Criteria andQualifierNotEqualTo(String value) {
            addCriterion("qualifier <>", value, "qualifier");
            return (Criteria) this;
        }

        public Criteria andQualifierGreaterThan(String value) {
            addCriterion("qualifier >", value, "qualifier");
            return (Criteria) this;
        }

        public Criteria andQualifierGreaterThanOrEqualTo(String value) {
            addCriterion("qualifier >=", value, "qualifier");
            return (Criteria) this;
        }

        public Criteria andQualifierLessThan(String value) {
            addCriterion("qualifier <", value, "qualifier");
            return (Criteria) this;
        }

        public Criteria andQualifierLessThanOrEqualTo(String value) {
            addCriterion("qualifier <=", value, "qualifier");
            return (Criteria) this;
        }

        public Criteria andQualifierLike(String value) {
            addCriterion("qualifier like", value, "qualifier");
            return (Criteria) this;
        }

        public Criteria andQualifierNotLike(String value) {
            addCriterion("qualifier not like", value, "qualifier");
            return (Criteria) this;
        }

        public Criteria andQualifierIn(List<String> values) {
            addCriterion("qualifier in", values, "qualifier");
            return (Criteria) this;
        }

        public Criteria andQualifierNotIn(List<String> values) {
            addCriterion("qualifier not in", values, "qualifier");
            return (Criteria) this;
        }

        public Criteria andQualifierBetween(String value1, String value2) {
            addCriterion("qualifier between", value1, value2, "qualifier");
            return (Criteria) this;
        }

        public Criteria andQualifierNotBetween(String value1, String value2) {
            addCriterion("qualifier not between", value1, value2, "qualifier");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table certification
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table certification
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}