package ca.studymedia.dao.mybatis.example;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CommentsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table comments
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table comments
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table comments
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated
     */
    public CommentsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table comments
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMaterialactivityUserUseridIsNull() {
            addCriterion("MaterialActivity_User_UserID is null");
            return (Criteria) this;
        }

        public Criteria andMaterialactivityUserUseridIsNotNull() {
            addCriterion("MaterialActivity_User_UserID is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialactivityUserUseridEqualTo(Integer value) {
            addCriterion("MaterialActivity_User_UserID =", value, "materialactivityUserUserid");
            return (Criteria) this;
        }

        public Criteria andMaterialactivityUserUseridNotEqualTo(Integer value) {
            addCriterion("MaterialActivity_User_UserID <>", value, "materialactivityUserUserid");
            return (Criteria) this;
        }

        public Criteria andMaterialactivityUserUseridGreaterThan(Integer value) {
            addCriterion("MaterialActivity_User_UserID >", value, "materialactivityUserUserid");
            return (Criteria) this;
        }

        public Criteria andMaterialactivityUserUseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("MaterialActivity_User_UserID >=", value, "materialactivityUserUserid");
            return (Criteria) this;
        }

        public Criteria andMaterialactivityUserUseridLessThan(Integer value) {
            addCriterion("MaterialActivity_User_UserID <", value, "materialactivityUserUserid");
            return (Criteria) this;
        }

        public Criteria andMaterialactivityUserUseridLessThanOrEqualTo(Integer value) {
            addCriterion("MaterialActivity_User_UserID <=", value, "materialactivityUserUserid");
            return (Criteria) this;
        }

        public Criteria andMaterialactivityUserUseridIn(List<Integer> values) {
            addCriterion("MaterialActivity_User_UserID in", values, "materialactivityUserUserid");
            return (Criteria) this;
        }

        public Criteria andMaterialactivityUserUseridNotIn(List<Integer> values) {
            addCriterion("MaterialActivity_User_UserID not in", values, "materialactivityUserUserid");
            return (Criteria) this;
        }

        public Criteria andMaterialactivityUserUseridBetween(Integer value1, Integer value2) {
            addCriterion("MaterialActivity_User_UserID between", value1, value2, "materialactivityUserUserid");
            return (Criteria) this;
        }

        public Criteria andMaterialactivityUserUseridNotBetween(Integer value1, Integer value2) {
            addCriterion("MaterialActivity_User_UserID not between", value1, value2, "materialactivityUserUserid");
            return (Criteria) this;
        }

        public Criteria andMaterialactivityMaterialMaterialidIsNull() {
            addCriterion("MaterialActivity_Material_MaterialID is null");
            return (Criteria) this;
        }

        public Criteria andMaterialactivityMaterialMaterialidIsNotNull() {
            addCriterion("MaterialActivity_Material_MaterialID is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialactivityMaterialMaterialidEqualTo(Integer value) {
            addCriterion("MaterialActivity_Material_MaterialID =", value, "materialactivityMaterialMaterialid");
            return (Criteria) this;
        }

        public Criteria andMaterialactivityMaterialMaterialidNotEqualTo(Integer value) {
            addCriterion("MaterialActivity_Material_MaterialID <>", value, "materialactivityMaterialMaterialid");
            return (Criteria) this;
        }

        public Criteria andMaterialactivityMaterialMaterialidGreaterThan(Integer value) {
            addCriterion("MaterialActivity_Material_MaterialID >", value, "materialactivityMaterialMaterialid");
            return (Criteria) this;
        }

        public Criteria andMaterialactivityMaterialMaterialidGreaterThanOrEqualTo(Integer value) {
            addCriterion("MaterialActivity_Material_MaterialID >=", value, "materialactivityMaterialMaterialid");
            return (Criteria) this;
        }

        public Criteria andMaterialactivityMaterialMaterialidLessThan(Integer value) {
            addCriterion("MaterialActivity_Material_MaterialID <", value, "materialactivityMaterialMaterialid");
            return (Criteria) this;
        }

        public Criteria andMaterialactivityMaterialMaterialidLessThanOrEqualTo(Integer value) {
            addCriterion("MaterialActivity_Material_MaterialID <=", value, "materialactivityMaterialMaterialid");
            return (Criteria) this;
        }

        public Criteria andMaterialactivityMaterialMaterialidIn(List<Integer> values) {
            addCriterion("MaterialActivity_Material_MaterialID in", values, "materialactivityMaterialMaterialid");
            return (Criteria) this;
        }

        public Criteria andMaterialactivityMaterialMaterialidNotIn(List<Integer> values) {
            addCriterion("MaterialActivity_Material_MaterialID not in", values, "materialactivityMaterialMaterialid");
            return (Criteria) this;
        }

        public Criteria andMaterialactivityMaterialMaterialidBetween(Integer value1, Integer value2) {
            addCriterion("MaterialActivity_Material_MaterialID between", value1, value2, "materialactivityMaterialMaterialid");
            return (Criteria) this;
        }

        public Criteria andMaterialactivityMaterialMaterialidNotBetween(Integer value1, Integer value2) {
            addCriterion("MaterialActivity_Material_MaterialID not between", value1, value2, "materialactivityMaterialMaterialid");
            return (Criteria) this;
        }

        public Criteria andMaterialactivityDateIsNull() {
            addCriterion("MaterialActivity_date is null");
            return (Criteria) this;
        }

        public Criteria andMaterialactivityDateIsNotNull() {
            addCriterion("MaterialActivity_date is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialactivityDateEqualTo(Date value) {
            addCriterion("MaterialActivity_date =", value, "materialactivityDate");
            return (Criteria) this;
        }

        public Criteria andMaterialactivityDateNotEqualTo(Date value) {
            addCriterion("MaterialActivity_date <>", value, "materialactivityDate");
            return (Criteria) this;
        }

        public Criteria andMaterialactivityDateGreaterThan(Date value) {
            addCriterion("MaterialActivity_date >", value, "materialactivityDate");
            return (Criteria) this;
        }

        public Criteria andMaterialactivityDateGreaterThanOrEqualTo(Date value) {
            addCriterion("MaterialActivity_date >=", value, "materialactivityDate");
            return (Criteria) this;
        }

        public Criteria andMaterialactivityDateLessThan(Date value) {
            addCriterion("MaterialActivity_date <", value, "materialactivityDate");
            return (Criteria) this;
        }

        public Criteria andMaterialactivityDateLessThanOrEqualTo(Date value) {
            addCriterion("MaterialActivity_date <=", value, "materialactivityDate");
            return (Criteria) this;
        }

        public Criteria andMaterialactivityDateIn(List<Date> values) {
            addCriterion("MaterialActivity_date in", values, "materialactivityDate");
            return (Criteria) this;
        }

        public Criteria andMaterialactivityDateNotIn(List<Date> values) {
            addCriterion("MaterialActivity_date not in", values, "materialactivityDate");
            return (Criteria) this;
        }

        public Criteria andMaterialactivityDateBetween(Date value1, Date value2) {
            addCriterion("MaterialActivity_date between", value1, value2, "materialactivityDate");
            return (Criteria) this;
        }

        public Criteria andMaterialactivityDateNotBetween(Date value1, Date value2) {
            addCriterion("MaterialActivity_date not between", value1, value2, "materialactivityDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table comments
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table comments
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}