package ca.studymedia.dao.mybatis.example;

import java.util.ArrayList;
import java.util.List;

public class MaterialExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table material
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table material
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table material
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbg.generated
     */
    public MaterialExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table material
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMaterialidIsNull() {
            addCriterion("MaterialID is null");
            return (Criteria) this;
        }

        public Criteria andMaterialidIsNotNull() {
            addCriterion("MaterialID is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialidEqualTo(Integer value) {
            addCriterion("MaterialID =", value, "materialid");
            return (Criteria) this;
        }

        public Criteria andMaterialidNotEqualTo(Integer value) {
            addCriterion("MaterialID <>", value, "materialid");
            return (Criteria) this;
        }

        public Criteria andMaterialidGreaterThan(Integer value) {
            addCriterion("MaterialID >", value, "materialid");
            return (Criteria) this;
        }

        public Criteria andMaterialidGreaterThanOrEqualTo(Integer value) {
            addCriterion("MaterialID >=", value, "materialid");
            return (Criteria) this;
        }

        public Criteria andMaterialidLessThan(Integer value) {
            addCriterion("MaterialID <", value, "materialid");
            return (Criteria) this;
        }

        public Criteria andMaterialidLessThanOrEqualTo(Integer value) {
            addCriterion("MaterialID <=", value, "materialid");
            return (Criteria) this;
        }

        public Criteria andMaterialidIn(List<Integer> values) {
            addCriterion("MaterialID in", values, "materialid");
            return (Criteria) this;
        }

        public Criteria andMaterialidNotIn(List<Integer> values) {
            addCriterion("MaterialID not in", values, "materialid");
            return (Criteria) this;
        }

        public Criteria andMaterialidBetween(Integer value1, Integer value2) {
            addCriterion("MaterialID between", value1, value2, "materialid");
            return (Criteria) this;
        }

        public Criteria andMaterialidNotBetween(Integer value1, Integer value2) {
            addCriterion("MaterialID not between", value1, value2, "materialid");
            return (Criteria) this;
        }

        public Criteria andResourceResourceidIsNull() {
            addCriterion("Resource_ResourceID is null");
            return (Criteria) this;
        }

        public Criteria andResourceResourceidIsNotNull() {
            addCriterion("Resource_ResourceID is not null");
            return (Criteria) this;
        }

        public Criteria andResourceResourceidEqualTo(Integer value) {
            addCriterion("Resource_ResourceID =", value, "resourceResourceid");
            return (Criteria) this;
        }

        public Criteria andResourceResourceidNotEqualTo(Integer value) {
            addCriterion("Resource_ResourceID <>", value, "resourceResourceid");
            return (Criteria) this;
        }

        public Criteria andResourceResourceidGreaterThan(Integer value) {
            addCriterion("Resource_ResourceID >", value, "resourceResourceid");
            return (Criteria) this;
        }

        public Criteria andResourceResourceidGreaterThanOrEqualTo(Integer value) {
            addCriterion("Resource_ResourceID >=", value, "resourceResourceid");
            return (Criteria) this;
        }

        public Criteria andResourceResourceidLessThan(Integer value) {
            addCriterion("Resource_ResourceID <", value, "resourceResourceid");
            return (Criteria) this;
        }

        public Criteria andResourceResourceidLessThanOrEqualTo(Integer value) {
            addCriterion("Resource_ResourceID <=", value, "resourceResourceid");
            return (Criteria) this;
        }

        public Criteria andResourceResourceidIn(List<Integer> values) {
            addCriterion("Resource_ResourceID in", values, "resourceResourceid");
            return (Criteria) this;
        }

        public Criteria andResourceResourceidNotIn(List<Integer> values) {
            addCriterion("Resource_ResourceID not in", values, "resourceResourceid");
            return (Criteria) this;
        }

        public Criteria andResourceResourceidBetween(Integer value1, Integer value2) {
            addCriterion("Resource_ResourceID between", value1, value2, "resourceResourceid");
            return (Criteria) this;
        }

        public Criteria andResourceResourceidNotBetween(Integer value1, Integer value2) {
            addCriterion("Resource_ResourceID not between", value1, value2, "resourceResourceid");
            return (Criteria) this;
        }

        public Criteria andTypeTypeidIsNull() {
            addCriterion("Type_TypeID is null");
            return (Criteria) this;
        }

        public Criteria andTypeTypeidIsNotNull() {
            addCriterion("Type_TypeID is not null");
            return (Criteria) this;
        }

        public Criteria andTypeTypeidEqualTo(Integer value) {
            addCriterion("Type_TypeID =", value, "typeTypeid");
            return (Criteria) this;
        }

        public Criteria andTypeTypeidNotEqualTo(Integer value) {
            addCriterion("Type_TypeID <>", value, "typeTypeid");
            return (Criteria) this;
        }

        public Criteria andTypeTypeidGreaterThan(Integer value) {
            addCriterion("Type_TypeID >", value, "typeTypeid");
            return (Criteria) this;
        }

        public Criteria andTypeTypeidGreaterThanOrEqualTo(Integer value) {
            addCriterion("Type_TypeID >=", value, "typeTypeid");
            return (Criteria) this;
        }

        public Criteria andTypeTypeidLessThan(Integer value) {
            addCriterion("Type_TypeID <", value, "typeTypeid");
            return (Criteria) this;
        }

        public Criteria andTypeTypeidLessThanOrEqualTo(Integer value) {
            addCriterion("Type_TypeID <=", value, "typeTypeid");
            return (Criteria) this;
        }

        public Criteria andTypeTypeidIn(List<Integer> values) {
            addCriterion("Type_TypeID in", values, "typeTypeid");
            return (Criteria) this;
        }

        public Criteria andTypeTypeidNotIn(List<Integer> values) {
            addCriterion("Type_TypeID not in", values, "typeTypeid");
            return (Criteria) this;
        }

        public Criteria andTypeTypeidBetween(Integer value1, Integer value2) {
            addCriterion("Type_TypeID between", value1, value2, "typeTypeid");
            return (Criteria) this;
        }

        public Criteria andTypeTypeidNotBetween(Integer value1, Integer value2) {
            addCriterion("Type_TypeID not between", value1, value2, "typeTypeid");
            return (Criteria) this;
        }

        public Criteria andSubtypeSubtypeidIsNull() {
            addCriterion("SubType_SubTypeID is null");
            return (Criteria) this;
        }

        public Criteria andSubtypeSubtypeidIsNotNull() {
            addCriterion("SubType_SubTypeID is not null");
            return (Criteria) this;
        }

        public Criteria andSubtypeSubtypeidEqualTo(Integer value) {
            addCriterion("SubType_SubTypeID =", value, "subtypeSubtypeid");
            return (Criteria) this;
        }

        public Criteria andSubtypeSubtypeidNotEqualTo(Integer value) {
            addCriterion("SubType_SubTypeID <>", value, "subtypeSubtypeid");
            return (Criteria) this;
        }

        public Criteria andSubtypeSubtypeidGreaterThan(Integer value) {
            addCriterion("SubType_SubTypeID >", value, "subtypeSubtypeid");
            return (Criteria) this;
        }

        public Criteria andSubtypeSubtypeidGreaterThanOrEqualTo(Integer value) {
            addCriterion("SubType_SubTypeID >=", value, "subtypeSubtypeid");
            return (Criteria) this;
        }

        public Criteria andSubtypeSubtypeidLessThan(Integer value) {
            addCriterion("SubType_SubTypeID <", value, "subtypeSubtypeid");
            return (Criteria) this;
        }

        public Criteria andSubtypeSubtypeidLessThanOrEqualTo(Integer value) {
            addCriterion("SubType_SubTypeID <=", value, "subtypeSubtypeid");
            return (Criteria) this;
        }

        public Criteria andSubtypeSubtypeidIn(List<Integer> values) {
            addCriterion("SubType_SubTypeID in", values, "subtypeSubtypeid");
            return (Criteria) this;
        }

        public Criteria andSubtypeSubtypeidNotIn(List<Integer> values) {
            addCriterion("SubType_SubTypeID not in", values, "subtypeSubtypeid");
            return (Criteria) this;
        }

        public Criteria andSubtypeSubtypeidBetween(Integer value1, Integer value2) {
            addCriterion("SubType_SubTypeID between", value1, value2, "subtypeSubtypeid");
            return (Criteria) this;
        }

        public Criteria andSubtypeSubtypeidNotBetween(Integer value1, Integer value2) {
            addCriterion("SubType_SubTypeID not between", value1, value2, "subtypeSubtypeid");
            return (Criteria) this;
        }

        public Criteria andUrlIsNull() {
            addCriterion("url is null");
            return (Criteria) this;
        }

        public Criteria andUrlIsNotNull() {
            addCriterion("url is not null");
            return (Criteria) this;
        }

        public Criteria andUrlEqualTo(String value) {
            addCriterion("url =", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotEqualTo(String value) {
            addCriterion("url <>", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThan(String value) {
            addCriterion("url >", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThanOrEqualTo(String value) {
            addCriterion("url >=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThan(String value) {
            addCriterion("url <", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThanOrEqualTo(String value) {
            addCriterion("url <=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLike(String value) {
            addCriterion("url like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotLike(String value) {
            addCriterion("url not like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlIn(List<String> values) {
            addCriterion("url in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotIn(List<String> values) {
            addCriterion("url not in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlBetween(String value1, String value2) {
            addCriterion("url between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotBetween(String value1, String value2) {
            addCriterion("url not between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table material
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table material
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}