package ca.studymedia.dao.mybatis.example;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ResourcesupportExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table resourcesupport
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table resourcesupport
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table resourcesupport
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourcesupport
     *
     * @mbg.generated
     */
    public ResourcesupportExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourcesupport
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourcesupport
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourcesupport
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourcesupport
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourcesupport
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourcesupport
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourcesupport
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourcesupport
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourcesupport
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourcesupport
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table resourcesupport
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserUseridIsNull() {
            addCriterion("User_UserID is null");
            return (Criteria) this;
        }

        public Criteria andUserUseridIsNotNull() {
            addCriterion("User_UserID is not null");
            return (Criteria) this;
        }

        public Criteria andUserUseridEqualTo(Integer value) {
            addCriterion("User_UserID =", value, "userUserid");
            return (Criteria) this;
        }

        public Criteria andUserUseridNotEqualTo(Integer value) {
            addCriterion("User_UserID <>", value, "userUserid");
            return (Criteria) this;
        }

        public Criteria andUserUseridGreaterThan(Integer value) {
            addCriterion("User_UserID >", value, "userUserid");
            return (Criteria) this;
        }

        public Criteria andUserUseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("User_UserID >=", value, "userUserid");
            return (Criteria) this;
        }

        public Criteria andUserUseridLessThan(Integer value) {
            addCriterion("User_UserID <", value, "userUserid");
            return (Criteria) this;
        }

        public Criteria andUserUseridLessThanOrEqualTo(Integer value) {
            addCriterion("User_UserID <=", value, "userUserid");
            return (Criteria) this;
        }

        public Criteria andUserUseridIn(List<Integer> values) {
            addCriterion("User_UserID in", values, "userUserid");
            return (Criteria) this;
        }

        public Criteria andUserUseridNotIn(List<Integer> values) {
            addCriterion("User_UserID not in", values, "userUserid");
            return (Criteria) this;
        }

        public Criteria andUserUseridBetween(Integer value1, Integer value2) {
            addCriterion("User_UserID between", value1, value2, "userUserid");
            return (Criteria) this;
        }

        public Criteria andUserUseridNotBetween(Integer value1, Integer value2) {
            addCriterion("User_UserID not between", value1, value2, "userUserid");
            return (Criteria) this;
        }

        public Criteria andResourceResourceidIsNull() {
            addCriterion("Resource_ResourceID is null");
            return (Criteria) this;
        }

        public Criteria andResourceResourceidIsNotNull() {
            addCriterion("Resource_ResourceID is not null");
            return (Criteria) this;
        }

        public Criteria andResourceResourceidEqualTo(Integer value) {
            addCriterion("Resource_ResourceID =", value, "resourceResourceid");
            return (Criteria) this;
        }

        public Criteria andResourceResourceidNotEqualTo(Integer value) {
            addCriterion("Resource_ResourceID <>", value, "resourceResourceid");
            return (Criteria) this;
        }

        public Criteria andResourceResourceidGreaterThan(Integer value) {
            addCriterion("Resource_ResourceID >", value, "resourceResourceid");
            return (Criteria) this;
        }

        public Criteria andResourceResourceidGreaterThanOrEqualTo(Integer value) {
            addCriterion("Resource_ResourceID >=", value, "resourceResourceid");
            return (Criteria) this;
        }

        public Criteria andResourceResourceidLessThan(Integer value) {
            addCriterion("Resource_ResourceID <", value, "resourceResourceid");
            return (Criteria) this;
        }

        public Criteria andResourceResourceidLessThanOrEqualTo(Integer value) {
            addCriterion("Resource_ResourceID <=", value, "resourceResourceid");
            return (Criteria) this;
        }

        public Criteria andResourceResourceidIn(List<Integer> values) {
            addCriterion("Resource_ResourceID in", values, "resourceResourceid");
            return (Criteria) this;
        }

        public Criteria andResourceResourceidNotIn(List<Integer> values) {
            addCriterion("Resource_ResourceID not in", values, "resourceResourceid");
            return (Criteria) this;
        }

        public Criteria andResourceResourceidBetween(Integer value1, Integer value2) {
            addCriterion("Resource_ResourceID between", value1, value2, "resourceResourceid");
            return (Criteria) this;
        }

        public Criteria andResourceResourceidNotBetween(Integer value1, Integer value2) {
            addCriterion("Resource_ResourceID not between", value1, value2, "resourceResourceid");
            return (Criteria) this;
        }

        public Criteria andDateIsNull() {
            addCriterion("date is null");
            return (Criteria) this;
        }

        public Criteria andDateIsNotNull() {
            addCriterion("date is not null");
            return (Criteria) this;
        }

        public Criteria andDateEqualTo(Date value) {
            addCriterion("date =", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotEqualTo(Date value) {
            addCriterion("date <>", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateGreaterThan(Date value) {
            addCriterion("date >", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateGreaterThanOrEqualTo(Date value) {
            addCriterion("date >=", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLessThan(Date value) {
            addCriterion("date <", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLessThanOrEqualTo(Date value) {
            addCriterion("date <=", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateIn(List<Date> values) {
            addCriterion("date in", values, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotIn(List<Date> values) {
            addCriterion("date not in", values, "date");
            return (Criteria) this;
        }

        public Criteria andDateBetween(Date value1, Date value2) {
            addCriterion("date between", value1, value2, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotBetween(Date value1, Date value2) {
            addCriterion("date not between", value1, value2, "date");
            return (Criteria) this;
        }

        public Criteria andDonationIsNull() {
            addCriterion("donation is null");
            return (Criteria) this;
        }

        public Criteria andDonationIsNotNull() {
            addCriterion("donation is not null");
            return (Criteria) this;
        }

        public Criteria andDonationEqualTo(BigDecimal value) {
            addCriterion("donation =", value, "donation");
            return (Criteria) this;
        }

        public Criteria andDonationNotEqualTo(BigDecimal value) {
            addCriterion("donation <>", value, "donation");
            return (Criteria) this;
        }

        public Criteria andDonationGreaterThan(BigDecimal value) {
            addCriterion("donation >", value, "donation");
            return (Criteria) this;
        }

        public Criteria andDonationGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("donation >=", value, "donation");
            return (Criteria) this;
        }

        public Criteria andDonationLessThan(BigDecimal value) {
            addCriterion("donation <", value, "donation");
            return (Criteria) this;
        }

        public Criteria andDonationLessThanOrEqualTo(BigDecimal value) {
            addCriterion("donation <=", value, "donation");
            return (Criteria) this;
        }

        public Criteria andDonationIn(List<BigDecimal> values) {
            addCriterion("donation in", values, "donation");
            return (Criteria) this;
        }

        public Criteria andDonationNotIn(List<BigDecimal> values) {
            addCriterion("donation not in", values, "donation");
            return (Criteria) this;
        }

        public Criteria andDonationBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("donation between", value1, value2, "donation");
            return (Criteria) this;
        }

        public Criteria andDonationNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("donation not between", value1, value2, "donation");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table resourcesupport
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table resourcesupport
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}