package ca.studymedia.dao.mybatis.example;

import java.util.ArrayList;
import java.util.List;

public class SubtypeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table subtype
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table subtype
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table subtype
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subtype
     *
     * @mbg.generated
     */
    public SubtypeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subtype
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subtype
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subtype
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subtype
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subtype
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subtype
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subtype
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subtype
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subtype
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subtype
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table subtype
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSubtypeidIsNull() {
            addCriterion("SubTypeID is null");
            return (Criteria) this;
        }

        public Criteria andSubtypeidIsNotNull() {
            addCriterion("SubTypeID is not null");
            return (Criteria) this;
        }

        public Criteria andSubtypeidEqualTo(Integer value) {
            addCriterion("SubTypeID =", value, "subtypeid");
            return (Criteria) this;
        }

        public Criteria andSubtypeidNotEqualTo(Integer value) {
            addCriterion("SubTypeID <>", value, "subtypeid");
            return (Criteria) this;
        }

        public Criteria andSubtypeidGreaterThan(Integer value) {
            addCriterion("SubTypeID >", value, "subtypeid");
            return (Criteria) this;
        }

        public Criteria andSubtypeidGreaterThanOrEqualTo(Integer value) {
            addCriterion("SubTypeID >=", value, "subtypeid");
            return (Criteria) this;
        }

        public Criteria andSubtypeidLessThan(Integer value) {
            addCriterion("SubTypeID <", value, "subtypeid");
            return (Criteria) this;
        }

        public Criteria andSubtypeidLessThanOrEqualTo(Integer value) {
            addCriterion("SubTypeID <=", value, "subtypeid");
            return (Criteria) this;
        }

        public Criteria andSubtypeidIn(List<Integer> values) {
            addCriterion("SubTypeID in", values, "subtypeid");
            return (Criteria) this;
        }

        public Criteria andSubtypeidNotIn(List<Integer> values) {
            addCriterion("SubTypeID not in", values, "subtypeid");
            return (Criteria) this;
        }

        public Criteria andSubtypeidBetween(Integer value1, Integer value2) {
            addCriterion("SubTypeID between", value1, value2, "subtypeid");
            return (Criteria) this;
        }

        public Criteria andSubtypeidNotBetween(Integer value1, Integer value2) {
            addCriterion("SubTypeID not between", value1, value2, "subtypeid");
            return (Criteria) this;
        }

        public Criteria andTypeTypeidIsNull() {
            addCriterion("Type_TypeID is null");
            return (Criteria) this;
        }

        public Criteria andTypeTypeidIsNotNull() {
            addCriterion("Type_TypeID is not null");
            return (Criteria) this;
        }

        public Criteria andTypeTypeidEqualTo(Integer value) {
            addCriterion("Type_TypeID =", value, "typeTypeid");
            return (Criteria) this;
        }

        public Criteria andTypeTypeidNotEqualTo(Integer value) {
            addCriterion("Type_TypeID <>", value, "typeTypeid");
            return (Criteria) this;
        }

        public Criteria andTypeTypeidGreaterThan(Integer value) {
            addCriterion("Type_TypeID >", value, "typeTypeid");
            return (Criteria) this;
        }

        public Criteria andTypeTypeidGreaterThanOrEqualTo(Integer value) {
            addCriterion("Type_TypeID >=", value, "typeTypeid");
            return (Criteria) this;
        }

        public Criteria andTypeTypeidLessThan(Integer value) {
            addCriterion("Type_TypeID <", value, "typeTypeid");
            return (Criteria) this;
        }

        public Criteria andTypeTypeidLessThanOrEqualTo(Integer value) {
            addCriterion("Type_TypeID <=", value, "typeTypeid");
            return (Criteria) this;
        }

        public Criteria andTypeTypeidIn(List<Integer> values) {
            addCriterion("Type_TypeID in", values, "typeTypeid");
            return (Criteria) this;
        }

        public Criteria andTypeTypeidNotIn(List<Integer> values) {
            addCriterion("Type_TypeID not in", values, "typeTypeid");
            return (Criteria) this;
        }

        public Criteria andTypeTypeidBetween(Integer value1, Integer value2) {
            addCriterion("Type_TypeID between", value1, value2, "typeTypeid");
            return (Criteria) this;
        }

        public Criteria andTypeTypeidNotBetween(Integer value1, Integer value2) {
            addCriterion("Type_TypeID not between", value1, value2, "typeTypeid");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table subtype
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table subtype
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}