package ca.studymedia.dao.mybatis.mapper;

import ca.studymedia.model.Certification;
import ca.studymedia.dao.mybatis.example.CertificationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CertificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certification
     *
     * @mbg.generated
     */
    long countByExample(CertificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certification
     *
     * @mbg.generated
     */
    int deleteByExample(CertificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certification
     *
     * @mbg.generated
     */
    int insert(Certification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certification
     *
     * @mbg.generated
     */
    int insertSelective(Certification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certification
     *
     * @mbg.generated
     */
    List<Certification> selectByExample(CertificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certification
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Certification record, @Param("example") CertificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certification
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Certification record, @Param("example") CertificationExample example);
}