package ca.studymedia.dao.mybatis.mapper;

import ca.studymedia.model.Resourcesupport;
import ca.studymedia.dao.mybatis.example.ResourcesupportExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ResourcesupportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourcesupport
     *
     * @mbg.generated
     */
    long countByExample(ResourcesupportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourcesupport
     *
     * @mbg.generated
     */
    int deleteByExample(ResourcesupportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourcesupport
     *
     * @mbg.generated
     */
    int insert(Resourcesupport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourcesupport
     *
     * @mbg.generated
     */
    int insertSelective(Resourcesupport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourcesupport
     *
     * @mbg.generated
     */
    List<Resourcesupport> selectByExample(ResourcesupportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourcesupport
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Resourcesupport record, @Param("example") ResourcesupportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourcesupport
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Resourcesupport record, @Param("example") ResourcesupportExample example);
}