package ca.studymedia.model;

public class Category {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.CategoryID
     *
     * @mbg.generated
     */
    private Integer categoryid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.description
     *
     * @mbg.generated
     */
    private String description;

    public Category() {
    }

    private Category(Builder builder) {
        setCategoryid(builder.categoryid);
        setName(builder.name);
        setDescription(builder.description);
    }

    public static Builder newBuilder() {
        return new Builder();
    }

    public static Builder newBuilder(Category copy) {
        Builder builder = new Builder();
        builder.categoryid = copy.categoryid;
        builder.name = copy.name;
        builder.description = copy.description;
        return builder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.CategoryID
     *
     * @return the value of category.CategoryID
     *
     * @mbg.generated
     */
    public Integer getCategoryid() {
        return categoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.CategoryID
     *
     * @param categoryid the value for category.CategoryID
     *
     * @mbg.generated
     */
    public void setCategoryid(Integer categoryid) {
        this.categoryid = categoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.name
     *
     * @return the value of category.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.name
     *
     * @param name the value for category.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.description
     *
     * @return the value of category.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.description
     *
     * @param description the value for category.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    public static final class Builder {
        private Integer categoryid;
        private String name;
        private String description;

        private Builder() {
        }

        public Builder withCategoryid(Integer val) {
            categoryid = val;
            return this;
        }

        public Builder withName(String val) {
            name = val;
            return this;
        }

        public Builder withDescription(String val) {
            description = val;
            return this;
        }

        public Category build() {
            return new Category(this);
        }
    }
}