package ca.studymedia.model;

import java.util.Date;

public class Certification {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certification.User_UserID
     *
     * @mbg.generated
     */
    private Integer userUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certification.Resource_ResourceID
     *
     * @mbg.generated
     */
    private Integer resourceResourceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certification.date
     *
     * @mbg.generated
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certification.grade
     *
     * @mbg.generated
     */
    private Integer grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certification.qualifier
     *
     * @mbg.generated
     */
    private String qualifier;

    public Certification() {
    }

    private Certification(Builder builder) {
        setUserUserid(builder.userUserid);
        setResourceResourceid(builder.resourceResourceid);
        setDate(builder.date);
        setGrade(builder.grade);
        setQualifier(builder.qualifier);
    }

    public static Builder newBuilder() {
        return new Builder();
    }

    public static Builder newBuilder(Certification copy) {
        Builder builder = new Builder();
        builder.userUserid = copy.userUserid;
        builder.resourceResourceid = copy.resourceResourceid;
        builder.date = copy.date;
        builder.grade = copy.grade;
        builder.qualifier = copy.qualifier;
        return builder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certification.User_UserID
     *
     * @return the value of certification.User_UserID
     *
     * @mbg.generated
     */
    public Integer getUserUserid() {
        return userUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certification.User_UserID
     *
     * @param userUserid the value for certification.User_UserID
     *
     * @mbg.generated
     */
    public void setUserUserid(Integer userUserid) {
        this.userUserid = userUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certification.Resource_ResourceID
     *
     * @return the value of certification.Resource_ResourceID
     *
     * @mbg.generated
     */
    public Integer getResourceResourceid() {
        return resourceResourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certification.Resource_ResourceID
     *
     * @param resourceResourceid the value for certification.Resource_ResourceID
     *
     * @mbg.generated
     */
    public void setResourceResourceid(Integer resourceResourceid) {
        this.resourceResourceid = resourceResourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certification.date
     *
     * @return the value of certification.date
     *
     * @mbg.generated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certification.date
     *
     * @param date the value for certification.date
     *
     * @mbg.generated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certification.grade
     *
     * @return the value of certification.grade
     *
     * @mbg.generated
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certification.grade
     *
     * @param grade the value for certification.grade
     *
     * @mbg.generated
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certification.qualifier
     *
     * @return the value of certification.qualifier
     *
     * @mbg.generated
     */
    public String getQualifier() {
        return qualifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certification.qualifier
     *
     * @param qualifier the value for certification.qualifier
     *
     * @mbg.generated
     */
    public void setQualifier(String qualifier) {
        this.qualifier = qualifier == null ? null : qualifier.trim();
    }

    public static final class Builder {
        private Integer userUserid;
        private Integer resourceResourceid;
        private Date date;
        private Integer grade;
        private String qualifier;

        private Builder() {
        }

        public Builder withUserUserid(Integer val) {
            userUserid = val;
            return this;
        }

        public Builder withResourceResourceid(Integer val) {
            resourceResourceid = val;
            return this;
        }

        public Builder withDate(Date val) {
            date = val;
            return this;
        }

        public Builder withGrade(Integer val) {
            grade = val;
            return this;
        }

        public Builder withQualifier(String val) {
            qualifier = val;
            return this;
        }

        public Certification build() {
            return new Certification(this);
        }
    }
}