package ca.studymedia.model;

import java.util.Date;

public class Comments {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.MaterialActivity_User_UserID
     *
     * @mbg.generated
     */
    private Integer materialactivityUserUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.MaterialActivity_Material_MaterialID
     *
     * @mbg.generated
     */
    private Integer materialactivityMaterialMaterialid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.MaterialActivity_date
     *
     * @mbg.generated
     */
    private Date materialactivityDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.comments
     *
     * @mbg.generated
     */
    private String comments;

    public Comments() {
    }

    private Comments(Builder builder) {
        setMaterialactivityUserUserid(builder.materialactivityUserUserid);
        setMaterialactivityMaterialMaterialid(builder.materialactivityMaterialMaterialid);
        setMaterialactivityDate(builder.materialactivityDate);
        setComments(builder.comments);
    }

    public static Builder newBuilder() {
        return new Builder();
    }

    public static Builder newBuilder(Comments copy) {
        Builder builder = new Builder();
        builder.materialactivityUserUserid = copy.materialactivityUserUserid;
        builder.materialactivityMaterialMaterialid = copy.materialactivityMaterialMaterialid;
        builder.materialactivityDate = copy.materialactivityDate;
        builder.comments = copy.comments;
        return builder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.MaterialActivity_User_UserID
     *
     * @return the value of comments.MaterialActivity_User_UserID
     *
     * @mbg.generated
     */
    public Integer getMaterialactivityUserUserid() {
        return materialactivityUserUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.MaterialActivity_User_UserID
     *
     * @param materialactivityUserUserid the value for comments.MaterialActivity_User_UserID
     *
     * @mbg.generated
     */
    public void setMaterialactivityUserUserid(Integer materialactivityUserUserid) {
        this.materialactivityUserUserid = materialactivityUserUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.MaterialActivity_Material_MaterialID
     *
     * @return the value of comments.MaterialActivity_Material_MaterialID
     *
     * @mbg.generated
     */
    public Integer getMaterialactivityMaterialMaterialid() {
        return materialactivityMaterialMaterialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.MaterialActivity_Material_MaterialID
     *
     * @param materialactivityMaterialMaterialid the value for comments.MaterialActivity_Material_MaterialID
     *
     * @mbg.generated
     */
    public void setMaterialactivityMaterialMaterialid(Integer materialactivityMaterialMaterialid) {
        this.materialactivityMaterialMaterialid = materialactivityMaterialMaterialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.MaterialActivity_date
     *
     * @return the value of comments.MaterialActivity_date
     *
     * @mbg.generated
     */
    public Date getMaterialactivityDate() {
        return materialactivityDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.MaterialActivity_date
     *
     * @param materialactivityDate the value for comments.MaterialActivity_date
     *
     * @mbg.generated
     */
    public void setMaterialactivityDate(Date materialactivityDate) {
        this.materialactivityDate = materialactivityDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.comments
     *
     * @return the value of comments.comments
     *
     * @mbg.generated
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.comments
     *
     * @param comments the value for comments.comments
     *
     * @mbg.generated
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }

    public static final class Builder {
        private Integer materialactivityUserUserid;
        private Integer materialactivityMaterialMaterialid;
        private Date materialactivityDate;
        private String comments;

        private Builder() {
        }

        public Builder withMaterialactivityUserUserid(Integer val) {
            materialactivityUserUserid = val;
            return this;
        }

        public Builder withMaterialactivityMaterialMaterialid(Integer val) {
            materialactivityMaterialMaterialid = val;
            return this;
        }

        public Builder withMaterialactivityDate(Date val) {
            materialactivityDate = val;
            return this;
        }

        public Builder withComments(String val) {
            comments = val;
            return this;
        }

        public Comments build() {
            return new Comments(this);
        }
    }
}