package ca.studymedia.model;

public class Material {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.MaterialID
     *
     * @mbg.generated
     */
    private Integer materialid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.Resource_ResourceID
     *
     * @mbg.generated
     */
    private Integer resourceResourceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.Type_TypeID
     *
     * @mbg.generated
     */
    private Integer typeTypeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.SubType_SubTypeID
     *
     * @mbg.generated
     */
    private Integer subtypeSubtypeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.description
     *
     * @mbg.generated
     */
    private String description;

    public Material() {
    }

    private Material(Builder builder) {
        setMaterialid(builder.materialid);
        setResourceResourceid(builder.resourceResourceid);
        setTypeTypeid(builder.typeTypeid);
        setSubtypeSubtypeid(builder.subtypeSubtypeid);
        setUrl(builder.url);
        setName(builder.name);
        setDescription(builder.description);
    }

    public static Builder newBuilder() {
        return new Builder();
    }

    public static Builder newBuilder(Material copy) {
        Builder builder = new Builder();
        builder.materialid = copy.materialid;
        builder.resourceResourceid = copy.resourceResourceid;
        builder.typeTypeid = copy.typeTypeid;
        builder.subtypeSubtypeid = copy.subtypeSubtypeid;
        builder.url = copy.url;
        builder.name = copy.name;
        builder.description = copy.description;
        return builder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.MaterialID
     *
     * @return the value of material.MaterialID
     *
     * @mbg.generated
     */
    public Integer getMaterialid() {
        return materialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.MaterialID
     *
     * @param materialid the value for material.MaterialID
     *
     * @mbg.generated
     */
    public void setMaterialid(Integer materialid) {
        this.materialid = materialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.Resource_ResourceID
     *
     * @return the value of material.Resource_ResourceID
     *
     * @mbg.generated
     */
    public Integer getResourceResourceid() {
        return resourceResourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.Resource_ResourceID
     *
     * @param resourceResourceid the value for material.Resource_ResourceID
     *
     * @mbg.generated
     */
    public void setResourceResourceid(Integer resourceResourceid) {
        this.resourceResourceid = resourceResourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.Type_TypeID
     *
     * @return the value of material.Type_TypeID
     *
     * @mbg.generated
     */
    public Integer getTypeTypeid() {
        return typeTypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.Type_TypeID
     *
     * @param typeTypeid the value for material.Type_TypeID
     *
     * @mbg.generated
     */
    public void setTypeTypeid(Integer typeTypeid) {
        this.typeTypeid = typeTypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.SubType_SubTypeID
     *
     * @return the value of material.SubType_SubTypeID
     *
     * @mbg.generated
     */
    public Integer getSubtypeSubtypeid() {
        return subtypeSubtypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.SubType_SubTypeID
     *
     * @param subtypeSubtypeid the value for material.SubType_SubTypeID
     *
     * @mbg.generated
     */
    public void setSubtypeSubtypeid(Integer subtypeSubtypeid) {
        this.subtypeSubtypeid = subtypeSubtypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.url
     *
     * @return the value of material.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.url
     *
     * @param url the value for material.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.name
     *
     * @return the value of material.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.name
     *
     * @param name the value for material.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.description
     *
     * @return the value of material.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.description
     *
     * @param description the value for material.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    public static final class Builder {
        private Integer materialid;
        private Integer resourceResourceid;
        private Integer typeTypeid;
        private Integer subtypeSubtypeid;
        private String url;
        private String name;
        private String description;

        private Builder() {
        }

        public Builder withMaterialid(Integer val) {
            materialid = val;
            return this;
        }

        public Builder withResourceResourceid(Integer val) {
            resourceResourceid = val;
            return this;
        }

        public Builder withTypeTypeid(Integer val) {
            typeTypeid = val;
            return this;
        }

        public Builder withSubtypeSubtypeid(Integer val) {
            subtypeSubtypeid = val;
            return this;
        }

        public Builder withUrl(String val) {
            url = val;
            return this;
        }

        public Builder withName(String val) {
            name = val;
            return this;
        }

        public Builder withDescription(String val) {
            description = val;
            return this;
        }

        public Material build() {
            return new Material(this);
        }
    }
}