package ca.studymedia.model;

import java.util.Date;

public class Materialactivity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materialactivity.User_UserID
     *
     * @mbg.generated
     */
    private Integer userUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materialactivity.Material_MaterialID
     *
     * @mbg.generated
     */
    private Integer materialMaterialid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materialactivity.date
     *
     * @mbg.generated
     */
    private Date date;

    public Materialactivity() {
    }

    private Materialactivity(Builder builder) {
        setUserUserid(builder.userUserid);
        setMaterialMaterialid(builder.materialMaterialid);
        setDate(builder.date);
    }

    public static Builder newBuilder() {
        return new Builder();
    }

    public static Builder newBuilder(Materialactivity copy) {
        Builder builder = new Builder();
        builder.userUserid = copy.userUserid;
        builder.materialMaterialid = copy.materialMaterialid;
        builder.date = copy.date;
        return builder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materialactivity.User_UserID
     *
     * @return the value of materialactivity.User_UserID
     *
     * @mbg.generated
     */
    public Integer getUserUserid() {
        return userUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materialactivity.User_UserID
     *
     * @param userUserid the value for materialactivity.User_UserID
     *
     * @mbg.generated
     */
    public void setUserUserid(Integer userUserid) {
        this.userUserid = userUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materialactivity.Material_MaterialID
     *
     * @return the value of materialactivity.Material_MaterialID
     *
     * @mbg.generated
     */
    public Integer getMaterialMaterialid() {
        return materialMaterialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materialactivity.Material_MaterialID
     *
     * @param materialMaterialid the value for materialactivity.Material_MaterialID
     *
     * @mbg.generated
     */
    public void setMaterialMaterialid(Integer materialMaterialid) {
        this.materialMaterialid = materialMaterialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materialactivity.date
     *
     * @return the value of materialactivity.date
     *
     * @mbg.generated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materialactivity.date
     *
     * @param date the value for materialactivity.date
     *
     * @mbg.generated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    public static final class Builder {
        private Integer userUserid;
        private Integer materialMaterialid;
        private Date date;

        private Builder() {
        }

        public Builder withUserUserid(Integer val) {
            userUserid = val;
            return this;
        }

        public Builder withMaterialMaterialid(Integer val) {
            materialMaterialid = val;
            return this;
        }

        public Builder withDate(Date val) {
            date = val;
            return this;
        }

        public Materialactivity build() {
            return new Materialactivity(this);
        }
    }
}