package ca.studymedia.model;

public class Resource {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.ResourceID
     *
     * @mbg.generated
     */
    private Integer resourceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.Category_CategoryID
     *
     * @mbg.generated
     */
    private Integer categoryCategoryid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.description
     *
     * @mbg.generated
     */
    private String description;

    public Resource() {
    }

    private Resource(Builder builder) {
        setResourceid(builder.resourceid);
        setCategoryCategoryid(builder.categoryCategoryid);
        setName(builder.name);
        setDescription(builder.description);
    }

    public static Builder newBuilder() {
        return new Builder();
    }

    public static Builder newBuilder(Resource copy) {
        Builder builder = new Builder();
        builder.resourceid = copy.resourceid;
        builder.categoryCategoryid = copy.categoryCategoryid;
        builder.name = copy.name;
        builder.description = copy.description;
        return builder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.ResourceID
     *
     * @return the value of resource.ResourceID
     *
     * @mbg.generated
     */
    public Integer getResourceid() {
        return resourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.ResourceID
     *
     * @param resourceid the value for resource.ResourceID
     *
     * @mbg.generated
     */
    public void setResourceid(Integer resourceid) {
        this.resourceid = resourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.Category_CategoryID
     *
     * @return the value of resource.Category_CategoryID
     *
     * @mbg.generated
     */
    public Integer getCategoryCategoryid() {
        return categoryCategoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.Category_CategoryID
     *
     * @param categoryCategoryid the value for resource.Category_CategoryID
     *
     * @mbg.generated
     */
    public void setCategoryCategoryid(Integer categoryCategoryid) {
        this.categoryCategoryid = categoryCategoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.name
     *
     * @return the value of resource.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.name
     *
     * @param name the value for resource.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.description
     *
     * @return the value of resource.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.description
     *
     * @param description the value for resource.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    public static final class Builder {
        private Integer resourceid;
        private Integer categoryCategoryid;
        private String name;
        private String description;

        private Builder() {
        }

        public Builder withResourceid(Integer val) {
            resourceid = val;
            return this;
        }

        public Builder withCategoryCategoryid(Integer val) {
            categoryCategoryid = val;
            return this;
        }

        public Builder withName(String val) {
            name = val;
            return this;
        }

        public Builder withDescription(String val) {
            description = val;
            return this;
        }

        public Resource build() {
            return new Resource(this);
        }
    }
}