package ca.studymedia.model;

import java.math.BigDecimal;
import java.util.Date;

public class Resourcesupport {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resourcesupport.User_UserID
     *
     * @mbg.generated
     */
    private Integer userUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resourcesupport.Resource_ResourceID
     *
     * @mbg.generated
     */
    private Integer resourceResourceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resourcesupport.date
     *
     * @mbg.generated
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resourcesupport.donation
     *
     * @mbg.generated
     */
    private BigDecimal donation;

    public Resourcesupport() {
    }

    private Resourcesupport(Builder builder) {
        setUserUserid(builder.userUserid);
        setResourceResourceid(builder.resourceResourceid);
        setDate(builder.date);
        setDonation(builder.donation);
    }

    public static Builder newBuilder() {
        return new Builder();
    }

    public static Builder newBuilder(Resourcesupport copy) {
        Builder builder = new Builder();
        builder.userUserid = copy.userUserid;
        builder.resourceResourceid = copy.resourceResourceid;
        builder.date = copy.date;
        builder.donation = copy.donation;
        return builder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resourcesupport.User_UserID
     *
     * @return the value of resourcesupport.User_UserID
     *
     * @mbg.generated
     */
    public Integer getUserUserid() {
        return userUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resourcesupport.User_UserID
     *
     * @param userUserid the value for resourcesupport.User_UserID
     *
     * @mbg.generated
     */
    public void setUserUserid(Integer userUserid) {
        this.userUserid = userUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resourcesupport.Resource_ResourceID
     *
     * @return the value of resourcesupport.Resource_ResourceID
     *
     * @mbg.generated
     */
    public Integer getResourceResourceid() {
        return resourceResourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resourcesupport.Resource_ResourceID
     *
     * @param resourceResourceid the value for resourcesupport.Resource_ResourceID
     *
     * @mbg.generated
     */
    public void setResourceResourceid(Integer resourceResourceid) {
        this.resourceResourceid = resourceResourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resourcesupport.date
     *
     * @return the value of resourcesupport.date
     *
     * @mbg.generated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resourcesupport.date
     *
     * @param date the value for resourcesupport.date
     *
     * @mbg.generated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resourcesupport.donation
     *
     * @return the value of resourcesupport.donation
     *
     * @mbg.generated
     */
    public BigDecimal getDonation() {
        return donation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resourcesupport.donation
     *
     * @param donation the value for resourcesupport.donation
     *
     * @mbg.generated
     */
    public void setDonation(BigDecimal donation) {
        this.donation = donation;
    }

    public static final class Builder {
        private Integer userUserid;
        private Integer resourceResourceid;
        private Date date;
        private BigDecimal donation;

        private Builder() {
        }

        public Builder withUserUserid(Integer val) {
            userUserid = val;
            return this;
        }

        public Builder withResourceResourceid(Integer val) {
            resourceResourceid = val;
            return this;
        }

        public Builder withDate(Date val) {
            date = val;
            return this;
        }

        public Builder withDonation(BigDecimal val) {
            donation = val;
            return this;
        }

        public Resourcesupport build() {
            return new Resourcesupport(this);
        }
    }
}