package ca.studymedia.model;

public class Subtype {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subtype.SubTypeID
     *
     * @mbg.generated
     */
    private Integer subtypeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subtype.Type_TypeID
     *
     * @mbg.generated
     */
    private Integer typeTypeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subtype.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subtype.description
     *
     * @mbg.generated
     */
    private String description;

    public Subtype() {
    }

    private Subtype(Builder builder) {
        setSubtypeid(builder.subtypeid);
        setTypeTypeid(builder.typeTypeid);
        setName(builder.name);
        setDescription(builder.description);
    }

    public static Builder newBuilder() {
        return new Builder();
    }

    public static Builder newBuilder(Subtype copy) {
        Builder builder = new Builder();
        builder.subtypeid = copy.subtypeid;
        builder.typeTypeid = copy.typeTypeid;
        builder.name = copy.name;
        builder.description = copy.description;
        return builder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subtype.SubTypeID
     *
     * @return the value of subtype.SubTypeID
     *
     * @mbg.generated
     */
    public Integer getSubtypeid() {
        return subtypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subtype.SubTypeID
     *
     * @param subtypeid the value for subtype.SubTypeID
     *
     * @mbg.generated
     */
    public void setSubtypeid(Integer subtypeid) {
        this.subtypeid = subtypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subtype.Type_TypeID
     *
     * @return the value of subtype.Type_TypeID
     *
     * @mbg.generated
     */
    public Integer getTypeTypeid() {
        return typeTypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subtype.Type_TypeID
     *
     * @param typeTypeid the value for subtype.Type_TypeID
     *
     * @mbg.generated
     */
    public void setTypeTypeid(Integer typeTypeid) {
        this.typeTypeid = typeTypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subtype.name
     *
     * @return the value of subtype.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subtype.name
     *
     * @param name the value for subtype.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subtype.description
     *
     * @return the value of subtype.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subtype.description
     *
     * @param description the value for subtype.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    public static final class Builder {
        private Integer subtypeid;
        private Integer typeTypeid;
        private String name;
        private String description;

        private Builder() {
        }

        public Builder withSubtypeid(Integer val) {
            subtypeid = val;
            return this;
        }

        public Builder withTypeTypeid(Integer val) {
            typeTypeid = val;
            return this;
        }

        public Builder withName(String val) {
            name = val;
            return this;
        }

        public Builder withDescription(String val) {
            description = val;
            return this;
        }

        public Subtype build() {
            return new Subtype(this);
        }
    }
}