package ca.studymedia.model;

import java.util.Date;

public class Comments {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.MaterialActivity_User_UserID
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    private Integer materialactivityUserUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.MaterialActivity_Material_MaterialID
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    private Integer materialactivityMaterialMaterialid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.MaterialActivity_date
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    private Date materialactivityDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.comments
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    private String comments;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.MaterialActivity_User_UserID
     *
     * @return the value of comments.MaterialActivity_User_UserID
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    public Integer getMaterialactivityUserUserid() {
        return materialactivityUserUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.MaterialActivity_User_UserID
     *
     * @param materialactivityUserUserid the value for comments.MaterialActivity_User_UserID
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    public void setMaterialactivityUserUserid(Integer materialactivityUserUserid) {
        this.materialactivityUserUserid = materialactivityUserUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.MaterialActivity_Material_MaterialID
     *
     * @return the value of comments.MaterialActivity_Material_MaterialID
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    public Integer getMaterialactivityMaterialMaterialid() {
        return materialactivityMaterialMaterialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.MaterialActivity_Material_MaterialID
     *
     * @param materialactivityMaterialMaterialid the value for comments.MaterialActivity_Material_MaterialID
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    public void setMaterialactivityMaterialMaterialid(Integer materialactivityMaterialMaterialid) {
        this.materialactivityMaterialMaterialid = materialactivityMaterialMaterialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.MaterialActivity_date
     *
     * @return the value of comments.MaterialActivity_date
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    public Date getMaterialactivityDate() {
        return materialactivityDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.MaterialActivity_date
     *
     * @param materialactivityDate the value for comments.MaterialActivity_date
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    public void setMaterialactivityDate(Date materialactivityDate) {
        this.materialactivityDate = materialactivityDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.comments
     *
     * @return the value of comments.comments
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.comments
     *
     * @param comments the value for comments.comments
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }
}