package ca.studymedia.model;

import java.util.Date;

public class Materialactivity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materialactivity.User_UserID
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    private Integer userUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materialactivity.Material_MaterialID
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    private Integer materialMaterialid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materialactivity.date
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    private Date date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materialactivity.User_UserID
     *
     * @return the value of materialactivity.User_UserID
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    public Integer getUserUserid() {
        return userUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materialactivity.User_UserID
     *
     * @param userUserid the value for materialactivity.User_UserID
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    public void setUserUserid(Integer userUserid) {
        this.userUserid = userUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materialactivity.Material_MaterialID
     *
     * @return the value of materialactivity.Material_MaterialID
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    public Integer getMaterialMaterialid() {
        return materialMaterialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materialactivity.Material_MaterialID
     *
     * @param materialMaterialid the value for materialactivity.Material_MaterialID
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    public void setMaterialMaterialid(Integer materialMaterialid) {
        this.materialMaterialid = materialMaterialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materialactivity.date
     *
     * @return the value of materialactivity.date
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materialactivity.date
     *
     * @param date the value for materialactivity.date
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    public void setDate(Date date) {
        this.date = date;
    }
}