package ca.studymedia.model;

public class Material {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.MaterialID
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    private Integer materialid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.Resource_ResourceID
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    private Integer resourceResourceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.Type_TypeID
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    private Integer typeTypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.SubType_SubTypeID
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    private Integer subtypeSubtypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.url
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.name
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.description
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.MaterialID
     *
     * @return the value of material.MaterialID
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    public Integer getMaterialid() {
        return materialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.MaterialID
     *
     * @param materialid the value for material.MaterialID
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    public void setMaterialid(Integer materialid) {
        this.materialid = materialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.Resource_ResourceID
     *
     * @return the value of material.Resource_ResourceID
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    public Integer getResourceResourceid() {
        return resourceResourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.Resource_ResourceID
     *
     * @param resourceResourceid the value for material.Resource_ResourceID
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    public void setResourceResourceid(Integer resourceResourceid) {
        this.resourceResourceid = resourceResourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.Type_TypeID
     *
     * @return the value of material.Type_TypeID
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    public Integer getTypeTypeid() {
        return typeTypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.Type_TypeID
     *
     * @param typeTypeid the value for material.Type_TypeID
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    public void setTypeTypeid(Integer typeTypeid) {
        this.typeTypeid = typeTypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.SubType_SubTypeID
     *
     * @return the value of material.SubType_SubTypeID
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    public Integer getSubtypeSubtypeid() {
        return subtypeSubtypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.SubType_SubTypeID
     *
     * @param subtypeSubtypeid the value for material.SubType_SubTypeID
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    public void setSubtypeSubtypeid(Integer subtypeSubtypeid) {
        this.subtypeSubtypeid = subtypeSubtypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.url
     *
     * @return the value of material.url
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.url
     *
     * @param url the value for material.url
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.name
     *
     * @return the value of material.name
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.name
     *
     * @param name the value for material.name
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.description
     *
     * @return the value of material.description
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.description
     *
     * @param description the value for material.description
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}