package ca.studymedia.model;

public class Resource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.ResourceID
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    private Integer resourceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.Category_CategoryID
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    private Integer categoryCategoryid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.name
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.description
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.ResourceID
     *
     * @return the value of resource.ResourceID
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    public Integer getResourceid() {
        return resourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.ResourceID
     *
     * @param resourceid the value for resource.ResourceID
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    public void setResourceid(Integer resourceid) {
        this.resourceid = resourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.Category_CategoryID
     *
     * @return the value of resource.Category_CategoryID
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    public Integer getCategoryCategoryid() {
        return categoryCategoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.Category_CategoryID
     *
     * @param categoryCategoryid the value for resource.Category_CategoryID
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    public void setCategoryCategoryid(Integer categoryCategoryid) {
        this.categoryCategoryid = categoryCategoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.name
     *
     * @return the value of resource.name
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.name
     *
     * @param name the value for resource.name
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.description
     *
     * @return the value of resource.description
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.description
     *
     * @param description the value for resource.description
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}