package ca.studymedia.model;

public class Subtype {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subtype.SubTypeID
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    private Integer subtypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subtype.Type_TypeID
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    private Integer typeTypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subtype.name
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subtype.description
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subtype.SubTypeID
     *
     * @return the value of subtype.SubTypeID
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    public Integer getSubtypeid() {
        return subtypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subtype.SubTypeID
     *
     * @param subtypeid the value for subtype.SubTypeID
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    public void setSubtypeid(Integer subtypeid) {
        this.subtypeid = subtypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subtype.Type_TypeID
     *
     * @return the value of subtype.Type_TypeID
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    public Integer getTypeTypeid() {
        return typeTypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subtype.Type_TypeID
     *
     * @param typeTypeid the value for subtype.Type_TypeID
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    public void setTypeTypeid(Integer typeTypeid) {
        this.typeTypeid = typeTypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subtype.name
     *
     * @return the value of subtype.name
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subtype.name
     *
     * @param name the value for subtype.name
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subtype.description
     *
     * @return the value of subtype.description
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subtype.description
     *
     * @param description the value for subtype.description
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}