package ca.studymedia.model;

public class Type {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.TypeID
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    private Integer typeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.name
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.description
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.TypeID
     *
     * @return the value of type.TypeID
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.TypeID
     *
     * @param typeid the value for type.TypeID
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.name
     *
     * @return the value of type.name
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.name
     *
     * @param name the value for type.name
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.description
     *
     * @return the value of type.description
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.description
     *
     * @param description the value for type.description
     *
     * @mbggenerated Tue Nov 12 11:57:25 EST 2013
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}